# Generated by Django 4.2.3 on 2023-07-07 07:56

import Stream.yandex_s3_storage
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0002_customuser_image_alter_musicianprofile_created_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('track_count', models.IntegerField(default=0)),
                ('duration_time', models.DurationField()),
                ('image', models.FileField(blank=True, null=True, storage=Stream.yandex_s3_storage.ClientDocsStorage(), upload_to='')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('musician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.musicianprofile', verbose_name='Музыкант')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Mood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('track_count', models.IntegerField(default=0)),
                ('duration_time', models.DurationField()),
                ('image', models.FileField(blank=True, null=True, storage=Stream.yandex_s3_storage.ClientDocsStorage(), upload_to='')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('is_favourites', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.FileField(blank=True, null=True, storage=Stream.yandex_s3_storage.ClientDocsStorage(), upload_to='')),
                ('track', models.FileField(blank=True, null=True, storage=Stream.yandex_s3_storage.ClientDocsStorage(), upload_to='')),
                ('duration', models.DurationField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='music.album', verbose_name='Альбом')),
                ('genre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='music.genre', verbose_name='Жанр')),
                ('mood', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='music.mood', verbose_name='Настроение')),
                ('musician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.musicianprofile', verbose_name='Создатель')),
            ],
        ),
        migrations.CreateModel(
            name='TrackInPlaylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.playlist', verbose_name='Плейлист')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.track', verbose_name='Трек')),
            ],
        ),
        migrations.CreateModel(
            name='LikeToAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_date', models.DateTimeField(auto_now_add=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.album', verbose_name='Альбом')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
